import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.hero}>
          <h1 className={styles.title}>
            Welcome to <span className={styles.gradient}>Next.js</span>
          </h1>
          <p className={styles.subtitle}>
            The React Framework for Production
          </p>
          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <div className={styles.cardIcon}>📚</div>
            <h3>Documentation</h3>
            <p>Find in-depth information about Next.js features and API.</p>
            <a href="https://nextjs.org/docs" className={styles.cardLink}>
              Learn more →
            </a>
          </div>

          <div className={styles.card}>
            <div className={styles.cardIcon}>🎓</div>
            <h3>Learn</h3>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            <a href="https://nextjs.org/learn" className={styles.cardLink}>
              Start learning →
            </a>
          </div>

          <div className={styles.card}>
            <div className={styles.cardIcon}>⚡</div>
            <h3>Examples</h3>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.cardLink}
            >
              Browse examples →
            </a>
          </div>

          <div className={styles.card}>
            <div className={styles.cardIcon}>🚀</div>
            <h3>Deploy</h3>
            <p>Deploy your Next.js app instantly with zero configuration.</p>
            <a
              href="https://docs.replit.com/category/deployments"
              className={styles.cardLink}
            >
              Deploy now →
            </a>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
